# Data
path: C:/!Lvasuk/Programing/qlSpineFixer/data
train: images/train  # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Keypoints
kpt_shape: [24, 2]  # [number of keypoints, number of dim]


# Classes
names:
  0: spine
